/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Chaitanya Krishnan (https://sketchfab.com/chaitanyak)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/fce16730b5de49a3a662961105ac3213
title: Sky Bus
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Material} geometry={nodes.Cube_0.geometry} />
        <mesh material={materials['Material.001']} geometry={nodes.Cube_1.geometry} />
        <mesh material={materials['Material.009']} geometry={nodes.Cube_2.geometry} />
        <mesh material={materials['Material.003']} geometry={nodes.Cube_3.geometry} />
        <mesh material={materials.flor_wood} geometry={nodes.Cube_4.geometry} />
        <group position={[0, 0, 1.11]}>
          <mesh material={materials.Material} geometry={nodes.Cube001_0.geometry} />
          <mesh material={materials['Material.001']} geometry={nodes.Cube001_1.geometry} />
          <mesh material={materials['Material.009']} geometry={nodes.Cube001_2.geometry} />
          <mesh material={materials.flor_wood} geometry={nodes.Cube001_3.geometry} />
        </group>
        <group position={[0.4, 0, 0.05]} scale={[0.85, 0.85, 0.85]}>
          <mesh material={materials['Material.002']} geometry={nodes.Cube002_0.geometry} />
          <mesh material={materials['Material.001']} geometry={nodes.Cube002_1.geometry} />
        </group>
        <group position={[0.26, 0, -0.14]} scale={[0.85, 0.85, 0.85]}>
          <mesh material={materials.Material} geometry={nodes.Cube003_0.geometry} />
        </group>
        <group position={[-1.13, 0.95, -0.62]} rotation={[-2.84, 0.92, -1.9]} scale={[0.3, 0.3, 0.3]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder002_0.geometry} />
          <mesh material={materials['Material.010']} geometry={nodes.Cylinder002_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder002_2.geometry} />
        </group>
        <group position={[-1.13, -0.87, -0.62]} rotation={[2.79, 0.91, -1.18]} scale={[-0.3, 0.3, 0.3]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder003_0.geometry} />
          <mesh material={materials['Material.010']} geometry={nodes.Cylinder003_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder003_2.geometry} />
        </group>
        <group position={[3.08, 0, -0.6]} rotation={[-Math.PI, 0.95, -Math.PI / 2]} scale={[0.3, 0.3, 0.3]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder005_0.geometry} />
          <mesh material={materials['Material.010']} geometry={nodes.Cylinder005_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder005_2.geometry} />
        </group>
        <group position={[-1.59, 0.83, -0.29]} rotation={[1.6, 0.2, 0]} scale={[0.58, 0.58, 0.58]}>
          <mesh material={materials['Material.003']} geometry={nodes.Sphere001_0.geometry} />
          <mesh material={materials['Material.005']} geometry={nodes.Sphere001_1.geometry} />
        </group>
        <group position={[-1.59, -0.76, -0.29]} rotation={[1.54, -0.24, 0]} scale={[0.58, 0.58, 0.58]}>
          <mesh material={materials['Material.003']} geometry={nodes.Sphere000_0.geometry} />
          <mesh material={materials['Material.005']} geometry={nodes.Sphere000_1.geometry} />
        </group>
        <group position={[2.68, 0.01, -0.29]} rotation={[Math.PI / 2, 0, 0]} scale={[0.58, 0.58, 0.58]}>
          <mesh material={materials['Material.003']} geometry={nodes.Sphere002_0.geometry} />
          <mesh material={materials['Material.005']} geometry={nodes.Sphere002_1.geometry} />
        </group>
        <group position={[-0.26, 0.01, 4.53]}>
          <mesh material={materials.Material} geometry={nodes.Cube004_0.geometry} />
          <mesh material={materials['Material.001']} geometry={nodes.Cube004_1.geometry} />
          <mesh material={materials['Material.009']} geometry={nodes.Cube004_2.geometry} />
          <mesh material={materials.flor_wood} geometry={nodes.Cube004_3.geometry} />
        </group>
        <group position={[2.9, 0, 1.12]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder001_0.geometry} />
        </group>
        <group position={[3.58, 1.16, 0.84]} rotation={[Math.PI, 1.56, -Math.PI / 2]} scale={[-0.09, 0.09, 0.09]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder004_0.geometry} />
          <mesh material={materials['Material.010']} geometry={nodes.Cylinder004_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder004_2.geometry} />
        </group>
        <group position={[3.58, -1.16, 0.84]} rotation={[Math.PI, 1.56, -Math.PI / 2]} scale={[0.09, 0.09, 0.09]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder006_0.geometry} />
          <mesh material={materials['Material.010']} geometry={nodes.Cylinder006_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder006_2.geometry} />
        </group>
        <group position={[-3.7, 0.36, 0.7]} rotation={[2.07, 1.51, -0.49]} scale={[0.17, 0.17, 0.17]}>
          <mesh material={materials['Material.002']} geometry={nodes.Sphere003_0.geometry} />
          <mesh material={materials['Material.007']} geometry={nodes.Sphere003_1.geometry} />
          <mesh material={materials['Material.008']} geometry={nodes.Sphere003_2.geometry} />
        </group>
        <group position={[-3.7, -0.35, 0.7]} rotation={[2.07, 1.51, -0.49]} scale={[0.17, 0.17, 0.17]}>
          <mesh material={materials['Material.002']} geometry={nodes.Sphere004_0.geometry} />
          <mesh material={materials['Material.007']} geometry={nodes.Sphere004_1.geometry} />
          <mesh material={materials['Material.008']} geometry={nodes.Sphere004_2.geometry} />
        </group>
        <group position={[-3.7, -0.35, 3.63]} rotation={[2.07, 1.51, -0.49]} scale={[0.17, 0.17, 0.17]}>
          <mesh material={materials['Material.002']} geometry={nodes.Sphere005_0.geometry} />
          <mesh material={materials['Material.007']} geometry={nodes.Sphere005_1.geometry} />
          <mesh material={materials['Material.008']} geometry={nodes.Sphere005_2.geometry} />
        </group>
        <group position={[-3.7, 0.36, 3.63]} rotation={[2.07, 1.51, -0.49]} scale={[0.17, 0.17, 0.17]}>
          <mesh material={materials['Material.002']} geometry={nodes.Sphere006_0.geometry} />
          <mesh material={materials['Material.007']} geometry={nodes.Sphere006_1.geometry} />
          <mesh material={materials['Material.008']} geometry={nodes.Sphere006_2.geometry} />
        </group>
        <group position={[2.91, 0.02, 5.4]} scale={[0.63, 0.63, 0.63]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder009_0.geometry} />
          <mesh material={materials['Material.002']} geometry={nodes.Cylinder009_1.geometry} />
        </group>
        <group position={[2.91, 0.22, 6.05]} rotation={[Math.PI / 2, 0, 0]} scale={[0.49, 0.49, 0.49]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder010_0.geometry} />
        </group>
        <group position={[3.24, 0.03, 5.4]} rotation={[0, -0.48, 0]} scale={[0.34, 0.34, 0.34]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder011_0.geometry} />
          <mesh material={materials['Material.002']} geometry={nodes.Cylinder011_1.geometry} />
        </group>
        <group position={[2.91, 0.02, 6.53]} scale={[0.09, 0.09, 0.09]}>
          <mesh material={materials['Material.003']} geometry={nodes.Cube005_0.geometry} />
          <mesh material={materials.Material} geometry={nodes.Cube005_1.geometry} />
        </group>
        <group position={[3.58, 1.15, 0.46]} rotation={[Math.PI, 1.56, -Math.PI / 2]} scale={[-0.09, 0.09, 0.09]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder012_0.geometry} />
          <mesh material={materials['Material.010']} geometry={nodes.Cylinder012_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder012_2.geometry} />
        </group>
        <group position={[3.58, -1.15, 0.46]} rotation={[Math.PI, 1.56, -Math.PI / 2]} scale={[0.09, 0.09, 0.09]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder013_0.geometry} />
          <mesh material={materials['Material.010']} geometry={nodes.Cylinder013_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder013_2.geometry} />
        </group>
        <group position={[3.2, 0.85, 2.48]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder007_0.geometry} />
          <mesh material={materials.material} geometry={nodes.Cylinder007_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder007_2.geometry} />
        </group>
        <group position={[3.2, 0.85, 2.58]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder008_0.geometry} />
          <mesh material={materials.material} geometry={nodes.Cylinder008_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder008_2.geometry} />
        </group>
        <group position={[3.2, 0.86, 3.69]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder014_0.geometry} />
          <mesh material={materials.material} geometry={nodes.Cylinder014_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder014_2.geometry} />
        </group>
        <group position={[3.2, 0.86, 3.59]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder015_0.geometry} />
          <mesh material={materials.material} geometry={nodes.Cylinder015_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder015_2.geometry} />
        </group>
        <group position={[3.31, 0.85, 0.7]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder016_0.geometry} />
          <mesh material={materials.material} geometry={nodes.Cylinder016_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder016_2.geometry} />
        </group>
        <group position={[3.31, 0.85, 0.59]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder017_0.geometry} />
          <mesh material={materials.material} geometry={nodes.Cylinder017_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder017_2.geometry} />
        </group>
        <group position={[3.31, -0.84, 0.59]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder018_0.geometry} />
          <mesh material={materials.material} geometry={nodes.Cylinder018_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder018_2.geometry} />
        </group>
        <group position={[3.31, -0.85, 0.7]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder019_0.geometry} />
          <mesh material={materials.material} geometry={nodes.Cylinder019_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder019_2.geometry} />
        </group>
        <group position={[3.2, -0.86, 3.59]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder020_0.geometry} />
          <mesh material={materials.material} geometry={nodes.Cylinder020_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder020_2.geometry} />
        </group>
        <group position={[3.2, -0.86, 3.69]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder021_0.geometry} />
          <mesh material={materials.material} geometry={nodes.Cylinder021_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder021_2.geometry} />
        </group>
        <group position={[3.2, -0.84, 2.58]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder022_0.geometry} />
          <mesh material={materials.material} geometry={nodes.Cylinder022_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder022_2.geometry} />
        </group>
        <group position={[3.2, -0.84, 2.48]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh material={materials['Material.005']} geometry={nodes.Cylinder023_0.geometry} />
          <mesh material={materials.material} geometry={nodes.Cylinder023_1.geometry} />
          <mesh material={materials['Material.003']} geometry={nodes.Cylinder023_2.geometry} />
        </group>
        <group position={[1.69, -0.84, 1.93]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube006_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube006_1.geometry} />
        </group>
        <group position={[1.69, -0.44, 1.93]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube007_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube007_1.geometry} />
        </group>
        <group position={[1.69, 0.79, 1.93]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube008_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube008_1.geometry} />
        </group>
        <group position={[1.69, 0.39, 1.93]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube009_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube009_1.geometry} />
        </group>
        <group position={[0.6, 0.79, 1.93]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube011_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube011_1.geometry} />
        </group>
        <group position={[0.6, -0.44, 1.93]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube012_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube012_1.geometry} />
        </group>
        <group position={[0.6, -0.84, 1.93]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube013_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube013_1.geometry} />
        </group>
        <group position={[-1.63, 0.39, 1.93]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube018_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube018_1.geometry} />
        </group>
        <group position={[-1.63, 0.79, 1.93]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube019_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube019_1.geometry} />
        </group>
        <group position={[-1.63, -0.42, 1.93]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube020_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube020_1.geometry} />
        </group>
        <group position={[-2.74, -0.84, 1.93]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube022_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube022_1.geometry} />
        </group>
        <group position={[-2.74, -0.44, 1.93]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube023_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube023_1.geometry} />
        </group>
        <group position={[-2.74, 0.79, 1.93]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube024_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube024_1.geometry} />
        </group>
        <group position={[-2.74, 0.39, 1.93]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube025_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube025_1.geometry} />
        </group>
        <group position={[-2.74, 0.39, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube026_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube026_1.geometry} />
        </group>
        <group position={[-2.74, 0.79, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube027_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube027_1.geometry} />
        </group>
        <group position={[-1.63, 0.79, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube032_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube032_1.geometry} />
        </group>
        <group position={[-1.63, 0.39, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube033_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube033_1.geometry} />
        </group>
        <group position={[-0.52, 0.39, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube034_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube034_1.geometry} />
        </group>
        <group position={[-0.52, 0.79, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube035_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube035_1.geometry} />
        </group>
        <group position={[0.6, 0.79, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube040_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube040_1.geometry} />
        </group>
        <group position={[0.6, 0.39, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube041_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube041_1.geometry} />
        </group>
        <group position={[1.69, 0.39, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube042_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube042_1.geometry} />
        </group>
        <group position={[1.69, 0.79, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube043_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube043_1.geometry} />
        </group>
        <group position={[0.6, -0.44, 0.81]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube052_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube052_1.geometry} />
        </group>
        <group position={[-0.52, -0.44, 0.81]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube055_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube055_1.geometry} />
        </group>
        <group position={[-1.63, 0.39, 0.81]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube058_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube058_1.geometry} />
        </group>
        <group position={[-1.63, -0.44, 0.81]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube060_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube060_1.geometry} />
        </group>
        <group position={[-2.6, -0.44, 0.81]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube063_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube063_1.geometry} />
        </group>
        <group position={[-2.6, 0.39, 0.81]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube065_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube065_1.geometry} />
        </group>
        <group position={[-3.05, -0.26, 4.58]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube046_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube046_1.geometry} />
        </group>
        <group position={[1.02, 0.38, 0.82]}>
          <group position={[-1.94, 0, 1.03]}>
            <mesh material={materials['Material.006']} geometry={nodes.step013_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step013_1.geometry} />
          </group>
          <group position={[-1.79, 0, 0.98]}>
            <mesh material={materials['Material.006']} geometry={nodes.step012_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step012_1.geometry} />
          </group>
          <group position={[-0.9, 0, 0.49]}>
            <mesh material={materials['Material.006']} geometry={nodes.step011_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step011_1.geometry} />
          </group>
          <group position={[-1.05, 0, 0.57]}>
            <mesh material={materials['Material.006']} geometry={nodes.step010_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step010_1.geometry} />
          </group>
          <group position={[-1.34, 0, 0.73]}>
            <mesh material={materials['Material.006']} geometry={nodes.step009_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step009_1.geometry} />
          </group>
          <group position={[-1.2, 0, 0.65]}>
            <mesh material={materials['Material.006']} geometry={nodes.step008_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step008_1.geometry} />
          </group>
          <group position={[-1.5, 0, 0.81]}>
            <mesh material={materials['Material.006']} geometry={nodes.step007_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step007_1.geometry} />
          </group>
          <group position={[-1.64, 0, 0.89]}>
            <mesh material={materials['Material.006']} geometry={nodes.step006_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step006_1.geometry} />
          </group>
          <group position={[-0.75, 0, 0.41]}>
            <mesh material={materials['Material.006']} geometry={nodes.step005_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step005_1.geometry} />
          </group>
          <group position={[-0.6, 0, 0.32]}>
            <mesh material={materials['Material.006']} geometry={nodes.step004_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step004_1.geometry} />
          </group>
          <group position={[-0.3, 0, 0.16]}>
            <mesh material={materials['Material.006']} geometry={nodes.step003_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step003_1.geometry} />
          </group>
          <group position={[-0.45, 0, 0.24]}>
            <mesh material={materials['Material.006']} geometry={nodes.step002_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step002_1.geometry} />
          </group>
          <group position={[-0.15, 0, 0.08]}>
            <mesh material={materials['Material.006']} geometry={nodes.step001_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step001_1.geometry} />
          </group>
          <mesh material={materials['Material.006']} geometry={nodes.step_0.geometry} />
          <mesh material={materials.Material} geometry={nodes.step_1.geometry} />
        </group>
        <group position={[-0.66, 0.42, 0.81]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube047_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube047_1.geometry} />
        </group>
        <group position={[0.53, 0.43, 0.83]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube016_0.geometry} />
        </group>
        <group position={[-1.16, -0.8, 1.92]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube017_0.geometry} />
        </group>
        <group position={[0.6, 0.39, 1.93]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube010_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube010_1.geometry} />
        </group>
        <group position={[-0.67, -0.85, 1.92]}>
          <group position={[-2.81, 0, 1.44]}>
            <mesh material={materials['Material.006']} geometry={nodes.step034_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step034_1.geometry} />
          </group>
          <group position={[-2.66, 0, 1.4]}>
            <mesh material={materials['Material.006']} geometry={nodes.step032_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step032_1.geometry} />
          </group>
          <group position={[-2.51, 0, 1.36]}>
            <mesh material={materials['Material.006']} geometry={nodes.step031_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step031_1.geometry} />
          </group>
          <group position={[-2.07, 0, 1.11]}>
            <mesh material={materials['Material.006']} geometry={nodes.step030_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step030_1.geometry} />
          </group>
          <group position={[-2.22, 0, 1.19]}>
            <mesh material={materials['Material.006']} geometry={nodes.step029_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step029_1.geometry} />
          </group>
          <group position={[-2.36, 0, 1.27]}>
            <mesh material={materials['Material.006']} geometry={nodes.step028_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step028_1.geometry} />
          </group>
          <group position={[-0.15, 0, 0.08]}>
            <mesh material={materials['Material.006']} geometry={nodes.step027_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step027_1.geometry} />
          </group>
          <group position={[-0.45, 0, 0.24]}>
            <mesh material={materials['Material.006']} geometry={nodes.step026_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step026_1.geometry} />
          </group>
          <group position={[-0.3, 0, 0.16]}>
            <mesh material={materials['Material.006']} geometry={nodes.step025_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step025_1.geometry} />
          </group>
          <group position={[-0.6, 0, 0.32]}>
            <mesh material={materials['Material.006']} geometry={nodes.step024_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step024_1.geometry} />
          </group>
          <group position={[-0.75, 0, 0.41]}>
            <mesh material={materials['Material.006']} geometry={nodes.step023_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step023_1.geometry} />
          </group>
          <group position={[-1.64, 0, 0.89]}>
            <mesh material={materials['Material.006']} geometry={nodes.step022_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step022_1.geometry} />
          </group>
          <group position={[-1.5, 0, 0.81]}>
            <mesh material={materials['Material.006']} geometry={nodes.step021_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step021_1.geometry} />
          </group>
          <group position={[-1.2, 0, 0.65]}>
            <mesh material={materials['Material.006']} geometry={nodes.step020_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step020_1.geometry} />
          </group>
          <group position={[-1.34, 0, 0.73]}>
            <mesh material={materials['Material.006']} geometry={nodes.step019_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step019_1.geometry} />
          </group>
          <group position={[-1.05, 0, 0.57]}>
            <mesh material={materials['Material.006']} geometry={nodes.step018_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step018_1.geometry} />
          </group>
          <group position={[-0.9, 0, 0.49]}>
            <mesh material={materials['Material.006']} geometry={nodes.step017_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step017_1.geometry} />
          </group>
          <group position={[-1.79, 0, 0.98]}>
            <mesh material={materials['Material.006']} geometry={nodes.step016_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step016_1.geometry} />
          </group>
          <group position={[-1.94, 0, 1.03]}>
            <mesh material={materials['Material.006']} geometry={nodes.step015_0.geometry} />
            <mesh material={materials.Material} geometry={nodes.step015_1.geometry} />
          </group>
          <mesh material={materials['Material.006']} geometry={nodes.step014_0.geometry} />
          <mesh material={materials.Material} geometry={nodes.step014_1.geometry} />
        </group>
        <group position={[2.41, 0.43, 3.43]} rotation={[0, 0, -Math.PI]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube014_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube014_1.geometry} />
        </group>
        <group position={[-1.63, -0.01, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube015_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube015_1.geometry} />
        </group>
        <group position={[-2.74, -0.01, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube028_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube028_1.geometry} />
        </group>
        <group position={[-0.52, -0.03, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube029_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube029_1.geometry} />
        </group>
        <group position={[1.69, -0.02, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube021_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube021_1.geometry} />
        </group>
        <group position={[0.6, -0.02, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube030_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube030_1.geometry} />
        </group>
        <group position={[2.41, 0.03, 3.43]} rotation={[0, 0, -Math.PI]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube031_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube031_1.geometry} />
        </group>
        <group position={[0.6, -0.84, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube036_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube036_1.geometry} />
        </group>
        <group position={[1.69, -0.84, 3.43]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube037_0.geometry} />
          <mesh material={materials['Material.011']} geometry={nodes.Cube037_1.geometry} />
        </group>
        <group position={[-0.52, -0.8, 3.44]} rotation={[0, -0.18, 0]}>
          <mesh material={materials['Material.006']} geometry={nodes.Cube038_0.geometry} />
        </group>
        <group position={[1.61, 1.12, 3.02]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.47, 0.47, 0.47]}>
          <mesh material={materials.Material} geometry={nodes.Text_0.geometry} />
        </group>
        <group position={[0.64, -1.12, 3.02]} rotation={[Math.PI / 2, 0, 0]} scale={[0.47, 0.47, 0.47]}>
          <mesh material={materials.Material} geometry={nodes.Text001_0.geometry} />
        </group>
        <group position={[4, -0.45, 4.72]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.47, 0.47, 0.47]}>
          <mesh material={materials.Material} geometry={nodes.Text002_0.geometry} />
        </group>
        <group position={[-4, 0.41, 3.03]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.41, 0.41, 0.41]}>
          <mesh material={materials.Material} geometry={nodes.Text003_0.geometry} />
        </group>
        <group position={[0, 1.25, -1.47]} rotation={[-1.56, -0.2, -0.93]} scale={[3.07, 3.07, 3.07]}>
          <mesh
            material={materials.Smoke_Transparent_Large_PNG_Image}
            geometry={nodes.Smoke_Transparent_Large_PNG_Image_0.geometry}
          />
        </group>
        <group position={[0, -1.15, -1.47]} rotation={[1.55, -0.18, -2.15]} scale={[3.07, 3.07, 3.07]}>
          <mesh
            material={materials.Smoke_Transparent_Large_PNG_Image}
            geometry={nodes.Smoke_Transparent_Large_PNG_Image001_0.geometry}
          />
        </group>
        <group position={[4.73, -0.03, -1.87]} rotation={[1.62, -0.07, -2.25]} scale={[4.34, 4.34, 4.34]}>
          <mesh
            material={materials.Smoke_Transparent_Large_PNG_Image}
            geometry={nodes.Smoke_Transparent_Large_PNG_Image002_0.geometry}
          />
        </group>
        <group position={[1.71, 3.74, -2.83]} rotation={[1.58, 0.02, -0.3]} scale={[13.72, 13.72, 13.72]}>
          <mesh
            material={materials['1515003598Smoke-PNG-Transparent-Image-3']}
            geometry={nodes['1515003598Smoke-PNG-Transparent-Image-3_0'].geometry}
          />
        </group>
        <group position={[6.24, -2.51, -3.03]} rotation={[1.58, 0.02, -0.3]} scale={[18.5, 18.5, 18.5]}>
          <mesh
            material={materials['1515003598Smoke-PNG-Transparent-Image-3']}
            geometry={nodes['1515003598Smoke-PNG-Transparent-Image-3001_0'].geometry}
          />
        </group>
        <group position={[-3.18, -2.05, -2.69]} rotation={[1.58, 0.02, -0.3]} scale={[8.59, 8.59, 8.59]}>
          <mesh
            material={materials['1515003598Smoke-PNG-Transparent-Image-3']}
            geometry={nodes['1515003598Smoke-PNG-Transparent-Image-3002_0'].geometry}
          />
        </group>
        <group position={[7.64, -2.52, -2.81]} rotation={[1.58, 0.02, -0.3]} scale={[11.06, 11.06, 11.06]}>
          <mesh
            material={materials['1515003598Smoke-PNG-Transparent-Image-3']}
            geometry={nodes['1515003598Smoke-PNG-Transparent-Image-3003_0'].geometry}
          />
        </group>
        <group position={[4.03, -1.11, 0.42]} rotation={[1.62, -0.04, -1.66]} scale={[1, 1, 1]}>
          <mesh
            material={materials.Smoke_Transparent_Large_PNG_Image}
            geometry={nodes.Smoke_Transparent_Large_PNG_Image003_0.geometry}
          />
        </group>
        <group position={[4.18, -1.11, 0.86]} rotation={[-1.53, -0.04, -1.66]} scale={[1, 1, 1]}>
          <mesh
            material={materials.Smoke_Transparent_Large_PNG_Image}
            geometry={nodes.Smoke_Transparent_Large_PNG_Image004_0.geometry}
          />
        </group>
        <group position={[4.18, 1.25, 0.49]} rotation={[-1.53, -0.04, -1.66]} scale={[1, 1, 1]}>
          <mesh
            material={materials.Smoke_Transparent_Large_PNG_Image}
            geometry={nodes.Smoke_Transparent_Large_PNG_Image005_0.geometry}
          />
        </group>
        <group position={[4.26, 1.19, 0.77]} rotation={[1.62, -0.04, -1.66]} scale={[1.26, 1.26, 1.26]}>
          <mesh
            material={materials.Smoke_Transparent_Large_PNG_Image}
            geometry={nodes.Smoke_Transparent_Large_PNG_Image006_0.geometry}
          />
        </group>
        <group position={[4.73, -0.18, -1.87]} rotation={[-1.58, 0.08, -0.92]} scale={[4.34, 4.34, 4.34]}>
          <mesh
            material={materials.Smoke_Transparent_Large_PNG_Image}
            geometry={nodes.Smoke_Transparent_Large_PNG_Image007_0.geometry}
          />
        </group>
        <group position={[-3.26, 0, 1.35]}>
          <mesh material={materials.glass} geometry={nodes.Cube039_0.geometry} />
          <mesh material={materials['glass.001']} geometry={nodes.Cube039_1.geometry} />
        </group>
        <group position={[-3.82, 0, 2.44]}>
          <mesh material={materials.glass} geometry={nodes.Cube044_0.geometry} />
          <mesh material={materials['glass.001']} geometry={nodes.Cube044_1.geometry} />
        </group>
        <group position={[-3.82, 0, 3.86]}>
          <mesh material={materials.glass} geometry={nodes.Cube045_0.geometry} />
          <mesh material={materials['glass.001']} geometry={nodes.Cube045_1.geometry} />
        </group>
        <group position={[-3.72, 0.01, 5.22]}>
          <mesh material={materials.glass} geometry={nodes.Cube048_0.geometry} />
          <mesh material={materials['glass.001']} geometry={nodes.Cube048_1.geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../scene.gltf')
