/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Hannes Delbeke (https://sketchfab.com/han)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/15c79bb2fc1147128039fe4ff90fd5a0
title: Fantasy Sky Background
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('./../../../fantasy-sky.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[0, 0, 0]}>
            <mesh
              material={materials.Material__25__background_JPG_002}
              geometry={nodes.Object001_Material__25__background_JPG_002_0.geometry}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./../../../fantasy-sky.gltf')
